trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  - group: PROD

steps:
- task: AzureCLI@1
  inputs:
    azureSubscription: 'azure-service-connection'
    scriptLocation: 'inlineScript'
    inlineScript: |
      param(
          [parameter(Mandatory = $true)][string]$aiResourceId,
          [parameter(Mandatory = $true)][string]$releaseName,
          [parameter(Mandatory = $false)]$releaseProperties = @()
      )
      
      $annotation = @{
          Id = [GUID]::NewGuid();
          AnnotationName = $releaseName;
          EventTime = (Get-Date).ToUniversalTime().GetDateTimeFormats("s")[0];
          Category = "Deployment";
          Properties = ConvertTo-Json $releaseProperties -Compress
      }
      
      $body = (ConvertTo-Json $annotation -Compress) -replace '(\\+)"', '$1$1"' -replace "`"", "`"`""
      # az rest --method put --uri "$($aiResourceId)/Annotations?api-version=2015-05-01" --body "$($body) "
      
      # Use the following command for Linux Azure DevOps Hosts or other PowerShell scenarios
      Invoke-AzRestMethod -Path "$aiResourceId/Annotations?api-version=2015-05-01" -Method PUT -Payload $body
    arguments: '-aiResourceId "<aiResourceId>" -releaseName "<releaseName>" -releaseProperties @{"ReleaseDescription"="<a description>"; "TriggerBy"="<Your name>" }'