# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- mainx

pool:
  vmImage: ubuntu-latest

variables:
  - group: PROD

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.6.2'
  displayName: 'Install Node.js 16.6.2'

- task: replacetokens@4
  displayName: 'Replace environment.prod.ts tokens'
  inputs:
    targetFiles: '**/environments/environment.*'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    useLegacyPattern: false
    enableTelemetry: true

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: ./FrontEnd

- task: PublishPipelineArtifact@1
  displayName: 'Publish Output'
  inputs:
    targetPath: FrontEnd
    artifact: FrontEnd
